### ISSUE TITLE
[bundlesdf.py] process frame 0000000 [pcl::PLYWriter::writeASCII] Input point cloud has no data! [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#38]
I am trying to run BundleSDF on my custom data that is captured using Intel RealSense D435 and have the mask created using XMem.

I am not sure what depth_processing should be set to.

```
depth_processing:
  zfar: 1.0
  erode:
    radius: 1
    diff: 0.001
    ratio: 0.8   #if ratio larger than this, depth set to 0
  bilateral_filter:
    radius: 2
    sigma_D: 2
    sigma_R: 100000
  outlier_removal:
    num: 30
    std_mul: 3
  edge_normal_thres: 10  #deg between normal and ray
  denoise_cloud: False
  percentile: 100
```
how do I find the values for depth_processing in ./BundleTrack/config_ho3d.yml ??

With no changes, I get this error: https://github.com/NVlabs/BundleSDF/issues/31

However, if I change the `depth>=0.1` to `depth>=0` in `bundlesdf.py`, I get this other error:
```
(py38) root@bundlesdf:/home/azureuser/BundleSDF# python run_custom.py --mode run_video --video_dir /home/azureuser/BundleSDF/my_obj/V00P00A00C00_trimmed/ --out_folder /home/azureuser/BundleSDF/my_obj/out --use_segmenter 1 --use_gui 0 --debug_level 2
[2023-07-10 07:48:16.591] [warning] [Bundler.cpp:49] Connected to nerf_port 9999
[2023-07-10 07:48:16.591] [warning] [FeatureManager.cpp:2084] Connected to port 5555
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
video dir is:  /home/azureuser/BundleSDF/my_obj/V00P00A00C00_trimmed/
type of color files:  <class 'list'>
len of color_files:  4203
stride is:  5
depth.shape is (480, 640, 3) and color.shape is (480, 640, 3)
mask.shape:  (480, 640, 3)
there are some non-zero elements in the mask
non zero in mask:  73957
&&&&&&&&&&&&&&&&&&&&&&&&&&&&
[bundlesdf.py] percentile denoise start
number of depth>=0:  381256
number of mask>0:  73957
number of True entries in valid:  73957
[bundlesdf.py] percentile denoise done
[bundlesdf.py] processNewFrame start 0000000
[bundlesdf.py] process frame 0000000
[pcl::PLYWriter::writeASCII] Input point cloud has no data!
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
[pcl::PLYWriter::writeASCII] Input point cloud has no data!
Segmentation fault (core dumped)
```

Could you please guide how to fix this error?
